FROM ubuntu:latest
RUN apt update -y && \
apt install gnupg wget -y && \
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add - && \
sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    /etc/apt/sources.list.d/jenkins.list' && \
apt update -y && \
apt install openjdk-11-jdk -y && \
apt-get install jenkins -y
CMD ["/usr/bin/java","-jar","/usr/share/jenkins/jenkins.war"]
