FROM amazoncorretto
RUN yum install wget -y && \
wget -O /etc/yum.repos.d/jenkins.repo \
https://pkg.jenkins.io/redhat-stable/jenkins.repo && \
rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key && \
yum upgrade -y && \
yum install jenkins -y
EXPOSE 8080
CMD ["/usr/bin/java","-jar","/usr/lib/jenkins/jenkins.war"]
